apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: trustee-operator
  namespace: trustee-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: stable
  name: trustee-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
  startingCSV: trustee-operator.v0.4.2
